# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whqwtSSdA9R5BSTW_njqBLjL7FVMpM87
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

data = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv")

y = data["meal"]
x = data.drop(columns=["meal", "id", "DateTime", "Total", "Discounts"])

model = RandomForestClassifier(n_estimators = 200, max_depth = 10, n_jobs = -1, class_weight = "balanced")

modelFit = model.fit(x, y)

tdata = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv")

test = tdata.drop(columns=["id", "DateTime"])

test = test.reindex(columns = x.columns)

predTest = modelFit.predict(test)

preddf = pd.DataFrame(predTest, columns = ["predict_meal"])

preddf["predict_meal"] = preddf["predict_meal"].astype(int)

pred = preddf["predict_meal"].tolist()

print(preddf.value_counts())